CREATE TABLE Player (
    Username VARCHAR(20) NOT NULL,
    Fname VARCHAR(20) NOT NULL,
    Lname VARCHAR(20) NOT NULL,
    Email VARCHAR(20) NOT NULL,
    Phone CHAR(10),
    ClubID INT,
    UsauID INT,
    Gender SMALLINT,
    PRIMARY KEY (Username)
);

CREATE TABLE Team (
    TeamID INT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(20) NOT NULL,
    Desc VARCHAR(255),
    Lat DOUBLE PRECISION NOT NULL,
    Long DOUBLE PRECISION NOT NULL,
    Host VARCHAR(20) NOT NULL,
    PRIMARY KEY (TeamID),
    CONSTRAINT HostFK FOREIGN KEY (Host) REFERENCES Player(Username)
        ON DELETE RESTRICT ON UPDATE CASCADE  
);

CREATE TABLE League (
    LeagueID INT NOT NULL AUTO_INCREMENT,
    Name VARCHAR(20) NOT NULL,
    Fee SMALLINT DEFAULT 0,
    Starts DATE,
    Ends DATE,
    Days CHAR(7),
    MinAge SMALLINT,
    MaxAge SMALLINT,
    PPT SMALLINT DEFAULT 21,
    Lat DOUBLE PRECISION NOT NULL,
    Long DOUBLE PRECISION NOT NULL,
    Host VARCHAR(20) NOT NULL,
    PRIMARY KEY (LeagueID),
    CONSTRAINT HostFK FOREIGN KEY (Host) REFERENCES Player(Username)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE LeagueTeam (
    TeamID INT NOT NULL,
    LeagueID INT NOT NULL,
    Skill SMALLINT,
    Captain VARCHAR(20),
    PRIMARY KEY (TeamID),
    CONSTRAINT TeamFK FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT LeagueFK FOREIGN KEY (LeagueID) REFERENCES League(LeagueID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CaptainFK FOREIGN KEY (Captain) REFERENCES Player(Username)
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE PickupTeam (
    TeamID INT NOT NULL,
    Fee SMALLINT DEFAULT 0,
    Days CHAR(7),
    Skill SMALLINT,
    MinAge SMALLINT,
    MaxAge SMALLINT,
    PRIMARY KEY (TeamID),
    CONSTRAINT TeamFK FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ClubTeam (
    TeamID INT NOT NULL,
    GenderDiv SMALLINT,
    AgeDiv SMALLINT,
    Captain VARCHAR(20),
    PRIMARY KEY (TeamID),
    CONSTRAINT TeamFK FOREIGN KEY (TeamID) REFERENCES Team(TeamID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT CaptainFK FOREIGN KEY (Captain) REFERENCES Player(Username)
        ON DELETE SET NULL ON UPDATE CASCADE
);

ALTER TABLE Player
    ADD CONSTRAINT ClubFK FOREIGN KEY (ClubID) REFERENCES ClubTeam(TeamID);

CREATE TABLE LeagueTeamPlayers (
    TeamID INT NOT NULL,
    Player VARCHAR(20) NOT NULL,
    PRIMARY KEY(TeamID, Player),
    CONSTRAINT TeamFK FOREIGN KEY (TeamID) REFERENCES LeagueTeam(TeamID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PlayerFK FOREIGN KEY (Player) REFERENCES Player(Username)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE PickupTeamPlayers (
    TeamID INT NOT NULL,
    Player VARCHAR(20) NOT NULL,
    PRIMARY KEY(TeamID, Player),
    CONSTRAINT TeamFK FOREIGN KEY (TeamID) REFERENCES PickupTeam(TeamID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT PlayerFK FOREIGN KEY (Player) REFERENCES Player(Username)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Follows (
    Player VARCHAR(20) NOT NULL,
    Follows VARCHAR(20) NOT NULL,
    PRIMARY KEY (Player, Follows),
    CONSTRAINT PlayerFK FOREIGN KEY (Player) REFERENCES Player(Username)
        ON DELETE CASCADE ON UPDATE CASCADE
    CONSTRAINT FollowsFK FOREIGN KEY (Follows) REFERENCES Player(Username)
        ON DELETE CASCADE ON UPDATE CASCADE
);